version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-street-food-app
    environment:
      - TZ=${TZ}
      - PORT=${PORT}
      - API_VERSION=${API_VERSION}
      - API_URL=${API_URL}
      - MONGO_DB=${MONGO_DB}
      - AMQP_URL=${AMQP_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_I=${JWT_EXPIRES_IN}
      - CLOUD_PLATFORM=${CLOUD_PLATFORM}
      - FILE_VALID_EXTENSIONS=${FILE_VALID_EXTENSIONS}
      - FILE_MAX_SIZE=${FILE_MAX_SIZE}
      - AWS_S3_ACCESS_KEY_ID=${AWS_S3_ACCESS_KEY_ID}
      - AWS_S3_SECRET_ACCESS_KEY=${AWS_S3_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - GCLOUD_PROJECT_ID=${GCLOUD_PROJECT_ID}
      - GCLOUD_TYPE=${GCLOUD_TYPE}
      - GCLOUD_PRIVATE_KEY_ID=${GCLOUD_PRIVATE_KEY_ID}
      - GCLOUD_PRIVATE_KEY=${GCLOUD_PRIVATE_KEY}
      - GCLOUD_CLIENT_EMAIL=${GCLOUD_CLIENT_EMAIL}
      - GCLOUD_CLIENT_ID=${GCLOUD_CLIENT_ID}
      - GCLOUD_AUTH_URI=${GCLOUD_AUTH_URI}
      - GCLOUD_TOKEN_URI=${GCLOUD_TOKEN_URI}
      - GCLOUD_AUTH_PROVIDER_X509_CERT_URL=${GCLOUD_AUTH_PROVIDER_X509_CERT_URL}
      - GCLOUD_CLIENT_X509_CERT_URL=${GCLOUD_CLIENT_X509_CERT_URL}
      - GCLOUD_UNIVERSE_DOMAIN=${GCLOUD_UNIVERSE_DOMAIN}
      - GCLOUD_STORAGE_ACCESS_KEY=${GCLOUD_STORAGE_ACCESS_KEY}
      - GCLOUD_STORAGE_SECRET_KEY=${GCLOUD_STORAGE_SECRET_KEY}
      - GCLOUD_STORAGE_BUCKET_NAME=${GCLOUD_STORAGE_BUCKET_NAME}
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src